apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  namespace: default
  labels:
    app: nginx
spec:
  containers:
    - name: nginx-container
      image: nginx
      ports:
        - containerPort: 80
      volumeMounts:
        - mountPath: /data
          name: volume-nginx
  volumes:
    - name: volume-nginx
      persistentVolumeClaim:
        claimName: pvc-nginx