apiVersion: v1
kind: Pod
metadata:
  name: busybox-pod
  labels:
    app: busybox
spec:
  volumes:
    - name: nginx-volume
      emptyDir:
        sizeLimit: 1Gi
  containers:
    - name: busybox-container
      image: busybox
      ports:
        - containerPort: 8080
      volumeMounts:
        - mountPath: /usr/share/nginx/html
          name: nginx-volume